# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sense_hat_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sense_hat_event.proto',
  package='custom.sensehat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15sense_hat_event.proto\x12\x0f\x63ustom.sensehat\"\x95\x01\n\rSenseHatEvent\x12\x35\n\x06header\x18\x01 \x01(\x0b\x32%.custom.sensehat.SenseHatEvent.Header\x12\x0f\n\x07payload\x18\x02 \x01(\t\x1a<\n\x06Header\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\tb\x06proto3')
)




_SENSEHATEVENT_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='custom.sensehat.SenseHatEvent.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='custom.sensehat.SenseHatEvent.Header.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='custom.sensehat.SenseHatEvent.Header.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageId', full_name='custom.sensehat.SenseHatEvent.Header.messageId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=192,
)

_SENSEHATEVENT = _descriptor.Descriptor(
  name='SenseHatEvent',
  full_name='custom.sensehat.SenseHatEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='custom.sensehat.SenseHatEvent.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='custom.sensehat.SenseHatEvent.payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SENSEHATEVENT_HEADER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=192,
)

_SENSEHATEVENT_HEADER.containing_type = _SENSEHATEVENT
_SENSEHATEVENT.fields_by_name['header'].message_type = _SENSEHATEVENT_HEADER
DESCRIPTOR.message_types_by_name['SenseHatEvent'] = _SENSEHATEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SenseHatEvent = _reflection.GeneratedProtocolMessageType('SenseHatEvent', (_message.Message,), dict(

  Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
    DESCRIPTOR = _SENSEHATEVENT_HEADER,
    __module__ = 'sense_hat_event_pb2'
    # @@protoc_insertion_point(class_scope:custom.sensehat.SenseHatEvent.Header)
    ))
  ,
  DESCRIPTOR = _SENSEHATEVENT,
  __module__ = 'sense_hat_event_pb2'
  # @@protoc_insertion_point(class_scope:custom.sensehat.SenseHatEvent)
  ))
_sym_db.RegisterMessage(SenseHatEvent)
_sym_db.RegisterMessage(SenseHatEvent.Header)


# @@protoc_insertion_point(module_scope)
